package os.nova.motion

import org.junit.Assert
import org.junit.BeforeClass
import org.junit.Test

/**
 * Golden-curve parity: the Kotlin port must reproduce the JS engine
 * (`prototype/src/motion/`) sample-for-sample. Curves are generated by
 * `tools/golden-curves.mjs`; `npm run check:port` keeps them fresh.
 *
 * Assertions are shared with `GoldenMain` in [NovaChecks].
 */
class NovaMotionGoldenTest {

    @Test
    fun constantsMatchTheJsReference() {
        val failures = NovaChecks.constantsFailures(golden)
        Assert.assertTrue(failures.joinToString("\n"), failures.isEmpty())
    }

    @Test
    fun everyProfileThemeSpringMatchesItsGoldenCurve() {
        val failures = NovaChecks.profileThemeFailures(golden)
        Assert.assertTrue(failures.joinToString("\n"), failures.isEmpty())
    }

    @Test
    fun releaseVelocitiesNeverBreakTheOvershootBudget() {
        val failures = NovaChecks.velocityFailures(golden)
        Assert.assertTrue(failures.joinToString("\n"), failures.isEmpty())
    }

    @Test
    fun reTargetMidFlightMatchesTheGoldenTrace() {
        val failures = NovaChecks.retargetFailures(golden)
        Assert.assertTrue(failures.joinToString("\n"), failures.isEmpty())
    }

    @Test
    fun guardsMatchTheGoldenHelpers() {
        val failures = NovaChecks.helperFailures(golden)
        Assert.assertTrue(failures.joinToString("\n"), failures.isEmpty())
    }

    companion object {
        private lateinit var golden: Map<String, Any?>

        @JvmStatic
        @BeforeClass
        fun loadGoldenOnce() {
            golden = NovaChecks.loadGolden()
        }
    }
}
